name: PR Build and Test

on:
  pull_request:
    branches:
      - main

jobs:
  fmt_clippy:
    name: fmt + clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd
      - uses: dtolnay/rust-toolchain@e97e2d8cc328f1b50210efc529dca0028893a2d9
        with:
          toolchain: 1.96.1
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@060bda31e0be4f453bb6ed2d7e5427b31734ad01
      - run: cargo fmt --all -- --check
      - run: cargo clippy --all-targets --locked -- -D warnings

  build_and_test:
    name: build + test (${{ matrix.target }})
    strategy:
      fail-fast: false
      matrix:
        target:
          - x86_64-unknown-linux-musl
          - aarch64-unknown-linux-musl
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd

      - name: Build and test binary
        uses: houseabsolute/actions-rust-cross@77a5caf54b78a8feb5c1d8d38744355e9c9b06aa
        with:
          command: both
          target: ${{ matrix.target }}
          args: "--release"
          strip: true
        env:
          CROSS_CONTAINER_OPTS: "-v /var/run/docker.sock:/var/run/docker.sock"